from typing import Any, Dict, List
import json

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.services.reports.pdf_report_service import (
    build_pdf_filename,
    get_pdf_output_path,
    get_report_styles,
    get_timestamp,
)


def to_safe_text(value: Any, fallback: str = "Not available") -> str:
    if value is None or value == "":
        return fallback

    if isinstance(value, (str, int, float, bool)):
        return str(value)

    if isinstance(value, list):
        parts = []
        for item in value:
            if isinstance(item, (str, int, float, bool)):
                parts.append(str(item))
            elif isinstance(item, dict):
                parts.append(
                    str(
                        item.get("title")
                        or item.get("action")
                        or item.get("recommendation")
                        or item.get("label")
                        or item.get("name")
                        or item
                    )
                )
            else:
                parts.append(str(item))
        return ", ".join(parts) if parts else fallback

    if isinstance(value, dict):
        return str(
            value.get("title")
            or value.get("action")
            or value.get("recommendation")
            or value.get("label")
            or value.get("name")
            or value
        )

    return str(value)


def build_decision_pdf(decisions: List[Dict[str, Any]]) -> str:
    filename = build_pdf_filename("decision_report")
    pdf_path = get_pdf_output_path(filename)

    styles = get_report_styles()
    story = []

    story.append(Paragraph("DataSpy Decision AI", styles["ReportTitleCustom"]))
    story.append(Paragraph("Key Decisions Report", styles["SectionHeadingCustom"]))
    story.append(Paragraph("Generated by: DataSpy Technologies", styles["MutedTextCustom"]))
    story.append(Paragraph(f"Generated at: {get_timestamp()}", styles["MutedTextCustom"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Executive Decision Summary", styles["SectionHeadingCustom"]))
    story.append(
        Paragraph(
            "This report presents the recommended actions generated by the decision engine. "
            "Each item includes business rationale, priority, and supporting evidence.",
            styles["BodyTextCustom"],
        )
    )

    overview_rows = [["Rank", "Priority", "Decision Type", "Action"]]

    for idx, item in enumerate(decisions, start=1):
        rank_order = item.get("rank_order") or idx
        priority = to_safe_text(item.get("priority"), "Unknown")
        decision_type = to_safe_text(item.get("category") or item.get("decision_type"), "General")
        action_text = to_safe_text(
            item.get("recommendation") or item.get("action") or item.get("title"),
            "Not available"
        )

        overview_rows.append([
            str(rank_order),
            priority,
            decision_type,
            action_text,
        ])

    story.append(Spacer(1, 10))
    story.append(Paragraph("Decision Overview Table", styles["SectionHeadingCustom"]))

    if len(overview_rows) > 1:
        table = Table(overview_rows, colWidths=[45, 75, 95, 285])
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dcfce7")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ])
        )
        story.append(table)
    else:
        story.append(Paragraph("No decisions available to display.", styles["BodyTextCustom"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph("Detailed Recommendations", styles["SectionHeadingCustom"]))

    for idx, decision in enumerate(decisions, start=1):
        title = to_safe_text(decision.get("title"), f"Decision {idx}")
        action_text = to_safe_text(
            decision.get("recommendation") or decision.get("action") or decision.get("title"),
            "Not available"
        )
        priority = to_safe_text(decision.get("priority"), "Unknown")
        decision_type = to_safe_text(decision.get("category") or decision.get("decision_type"), "General")
        rank_order = to_safe_text(decision.get("rank_order"), str(idx))
        rationale = to_safe_text(
            decision.get("reasoning", {}).get("why")
            if isinstance(decision.get("reasoning"), dict)
            else None
        )
        if rationale == "Not available":
            rationale = to_safe_text(decision.get("rationale") or decision.get("reason"))

        explanation = to_safe_text(decision.get("explanation"))
        forecast_support = to_safe_text(decision.get("forecast_support"))
        ignored_text = to_safe_text(
            decision.get("reasoning", {}).get("what_happens_if_ignored")
            if isinstance(decision.get("reasoning"), dict)
            else None
        )

        confidence_label = to_safe_text(
            decision.get("confidence", {}).get("label")
            if isinstance(decision.get("confidence"), dict)
            else None,
            "Unknown"
        )
        confidence_score = decision.get("confidence", {}).get("score") if isinstance(decision.get("confidence"), dict) else None

        impact_label = to_safe_text(
            decision.get("impact_estimate", {}).get("label")
            if isinstance(decision.get("impact_estimate"), dict)
            else None,
            "Unknown"
        )
        impact_score = decision.get("impact_estimate", {}).get("score") if isinstance(decision.get("impact_estimate"), dict) else None

        evidence = decision.get("supporting_evidence") or decision.get("evidence") or {}

        story.append(Paragraph(f"{idx}. {title}", styles["BodyTextCustom"]))
        story.append(Paragraph(f"Recommended Action: {action_text}", styles["BodyTextCustom"]))
        story.append(Paragraph(f"Priority: {priority}", styles["BodyTextCustom"]))
        story.append(Paragraph(f"Decision Type: {decision_type}", styles["BodyTextCustom"]))
        story.append(Paragraph(f"Rank Order: {rank_order}", styles["BodyTextCustom"]))
        story.append(Paragraph(f"Rationale: {rationale}", styles["BodyTextCustom"]))

        if explanation != "Not available":
            story.append(Paragraph(f"Business Explanation: {explanation}", styles["BodyTextCustom"]))

        if forecast_support != "Not available":
            story.append(Paragraph(f"Forecast Support: {forecast_support}", styles["BodyTextCustom"]))

        if ignored_text != "Not available":
            story.append(Paragraph(f"What Happens If Ignored: {ignored_text}", styles["BodyTextCustom"]))

        if confidence_score is not None:
            story.append(Paragraph(
                f"Confidence: {confidence_label} ({round(float(confidence_score) * 100, 1)}%)",
                styles["BodyTextCustom"],
            ))
        else:
            story.append(Paragraph(f"Confidence: {confidence_label}", styles["BodyTextCustom"]))

        if impact_score is not None:
            story.append(Paragraph(
                f"Impact Estimate: {impact_label} ({round(float(impact_score) * 100, 1)}%)",
                styles["BodyTextCustom"],
            ))
        else:
            story.append(Paragraph(f"Impact Estimate: {impact_label}", styles["BodyTextCustom"]))

        if evidence:
            story.append(Paragraph("Supporting Evidence:", styles["BodyTextCustom"]))
            evidence_text = json.dumps(evidence, indent=2, ensure_ascii=False)
            story.append(Paragraph(evidence_text.replace("\n", "<br/>"), styles["BodyTextCustom"]))

        story.append(Spacer(1, 10))

    doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
    doc.build(story)

    return str(pdf_path)