from typing import Any, Dict, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)

from app.services.reports.pdf_report_service import (
    build_pdf_filename,
    get_pdf_output_path,
    get_report_styles,
    get_timestamp,
)
from app.services.reports.report_chart_builder import generate_forecast_chart


def extract_point(row: Dict[str, Any], default_index: int = 0) -> Tuple[str, Any]:
    """
    Extract a displayable date/label and value from a forecast row.
    Supports multiple possible key names because forecast payloads can vary.
    """
    if not isinstance(row, dict):
        return f"T{default_index + 1}", ""

    date_value = (
        row.get("date")
        or row.get("ds")
        or row.get("timestamp")
        or row.get("period")
        or row.get("label")
        or row.get("x")
        or row.get("date_label")
        or row.get("time")
        or row.get("index")
        or f"T{default_index + 1}"
    )

    value = (
        row.get("value")
        if row.get("value") is not None
        else row.get("forecast")
        if row.get("forecast") is not None
        else row.get("predicted_value")
        if row.get("predicted_value") is not None
        else row.get("yhat")
        if row.get("yhat") is not None
        else row.get("target_value")
        if row.get("target_value") is not None
        else row.get("actual")
        if row.get("actual") is not None
        else row.get("y")
        if row.get("y") is not None
        else row.get("forecast_value")
        if row.get("forecast_value") is not None
        else row.get("predicted")
        if row.get("predicted") is not None
        else row.get("amount")
        if row.get("amount") is not None
        else ""
    )

    return str(date_value), value


def build_forecast_pdf(forecast: Dict[str, Any]) -> str:
    filename = build_pdf_filename("forecast_report")
    pdf_path = get_pdf_output_path(filename)

    styles = get_report_styles()
    story = []

    historical_series = (
        forecast.get("historical_series")
        or forecast.get("history")
        or forecast.get("historical")
        or forecast.get("actual_series")
        or []
    )

    forecast_series = (
        forecast.get("forecast_series")
        or forecast.get("predictions")
        or forecast.get("future_series")
        or forecast.get("projected_series")
        or []
    )

    forecast_target_role = (
        forecast.get("forecast_target_role")
        or forecast.get("target_role")
        or forecast.get("target_column")
        or forecast.get("metric")
        or forecast.get("forecast_target")
        or "Not available"
    )

    forecast_horizon = (
        forecast.get("forecast_horizon")
        or forecast.get("horizon")
        or forecast.get("periods")
        or len(forecast_series)
        or "Not available"
    )

    model_used = (
        forecast.get("model_used")
        or forecast.get("selected_model")
        or forecast.get("model_name")
        or "Not available"
    )

    reliability_label = (
        forecast.get("reliability_label")
        or (
            forecast.get("reliability", {}).get("label")
            if isinstance(forecast.get("reliability"), dict)
            else None
        )
        or "Not available"
    )

    warnings = forecast.get("warnings", []) or []
    trend = forecast.get("trend")
    growth_percent = forecast.get("growth_percent")

    story.append(Paragraph("DataSpy Decision AI", styles["ReportTitleCustom"]))
    story.append(Paragraph("Forecast Report", styles["SectionHeadingCustom"]))
    story.append(Paragraph("Generated by: DataSpy Technologies", styles["MutedTextCustom"]))
    story.append(Paragraph(f"Generated at: {get_timestamp()}", styles["MutedTextCustom"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Forecast Overview", styles["SectionHeadingCustom"]))
    story.append(Paragraph(f"Forecast Target: {forecast_target_role}", styles["BodyTextCustom"]))
    story.append(Paragraph(f"Forecast Horizon: {forecast_horizon}", styles["BodyTextCustom"]))
    story.append(Paragraph(f"Model Used: {model_used}", styles["BodyTextCustom"]))
    story.append(Paragraph(f"Reliability Label: {reliability_label}", styles["BodyTextCustom"]))

    if trend not in [None, ""]:
        story.append(Paragraph(f"Trend: {trend}", styles["BodyTextCustom"]))

    if growth_percent not in [None, ""]:
        story.append(Paragraph(f"Growth %: {growth_percent}", styles["BodyTextCustom"]))

    story.append(Spacer(1, 8))
    story.append(Paragraph("Warnings", styles["SectionHeadingCustom"]))
    if warnings:
        for warning in warnings:
            story.append(Paragraph(f"• {warning}", styles["BodyTextCustom"]))
    else:
        story.append(Paragraph("No forecast warnings available.", styles["BodyTextCustom"]))

    if historical_series or forecast_series:
        chart_path = generate_forecast_chart(
            historical_series=historical_series,
            forecast_series=forecast_series,
        )

        story.append(Spacer(1, 12))
        story.append(Paragraph("Forecast Chart", styles["SectionHeadingCustom"]))
        story.append(Image(chart_path, width=500, height=260))

    table_rows = [["Series Type", "Date", "Value"]]

    for idx, row in enumerate(historical_series):
        date_value, point_value = extract_point(row, idx)
        table_rows.append([
            "historical",
            date_value,
            str(point_value),
        ])

    for idx, row in enumerate(forecast_series):
        date_value, point_value = extract_point(row, idx)
        table_rows.append([
            "forecast",
            date_value,
            str(point_value),
        ])

    story.append(Spacer(1, 12))
    story.append(Paragraph("Forecast Data Table", styles["SectionHeadingCustom"]))

    if len(table_rows) > 1:
        table = Table(table_rows, colWidths=[100, 180, 140])
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dbeafe")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ])
        )
        story.append(table)
    else:
        story.append(Paragraph("No forecast series available to display.", styles["BodyTextCustom"]))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Business Note", styles["SectionHeadingCustom"]))
    story.append(
        Paragraph(
            "This forecast report summarizes historical and projected values generated by DataSpy Decision AI. "
            "Management should review reliability indicators and forecast warnings before taking action.",
            styles["BodyTextCustom"],
        )
    )

    doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
    doc.build(story)

    return str(pdf_path)